package com.web.enums;

public enum ConfigProperties {

    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS,
    RETRYFAILEDTESTS,
    RUNMODE,
    GRIDURL,
    ELKURL,
    SENDRESULTSTOELK
}
